<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 C:\Users\Utente\Desktop\Trasferimento-PC\Projects\Youtube\Threlte\spaceship-header\static\models\spaceship.glb --root /models/ --printwidth 120 --precision 2
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rusty-spaceship-orange-18541ebed6ce44a9923f9b8dc30d87f5
Title: Rusty Spaceship - Orange
-->
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { AddEquation, CustomBlending, Group, LessEqualDepth, Material, OneFactor } from 'three'
  import { T } from '@threlte/core'
  import { useGltf, useDraco, useTexture } from '@threlte/extras'

  interface Props {
    ref?: Group
    fallback?: Snippet
    error?: Snippet<[any]>
    children?: Snippet<[any]>
    [key: string]: any
  }

  let { fallback, error, children, ref = $bindable(), ...props }: Props = $props()

  const dracoLoader = useDraco()
  const gltf = useGltf('/spaceship-tutorial/models/spaceship-transformed.glb', {
    dracoLoader
  })
  const map = useTexture('/spaceship-tutorial/textures/energy-beam-opacity.png')

  function alphaFix(material: Material) {
    material.transparent = true
    material.alphaToCoverage = true
    material.depthFunc = LessEqualDepth
    material.depthTest = true
    material.depthWrite = true
  }

  gltf.then((model) => {
    alphaFix(model.materials.spaceship_racer)
    alphaFix(model.materials.cockpit)
  })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      scale={0.003}
      rotation={[0, -Math.PI * 0.5, 0]}
      position={[0.95, 0, 0]}
    >
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube001_spaceship_racer_0.geometry}
        material={gltf.materials.spaceship_racer}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube005_cockpit_0.geometry}
        material={gltf.materials.cockpit}
      />

      {#await map then mapValue}
        <T.Mesh
          position={[0, 0, -1350]}
          rotation.x={Math.PI * 0.5}
        >
          <T.CylinderGeometry args={[70, 25, 1600, 15]} />
          <T.MeshBasicMaterial
            color={[1.0, 0.4, 0.02]}
            alphaMap={mapValue}
            transparent
            blending={CustomBlending}
            blendDst={OneFactor}
            blendEquation={AddEquation}
          />
        </T.Mesh>
      {/await}
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
