packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  three: ^0.175.0
  "@types/three": ^0.175.0
  svelte: "^5.26.2"
  typescript: "^5.6.3"
  vite: "^5.2.8"
  "@types/node": "^20.12.7"
  "@eslint/js": "^9.26.0"
  "eslint": "^9.26.0"
  "@sveltejs/adapter-auto": "^3.3.1"
  "@sveltejs/kit": "^2.7.7"
  "@sveltejs/package": "^2.3.7"
  "@sveltejs/vite-plugin-svelte": "^4.0.0"
  "@yushijinhun/three-minifier-rollup": "^0.4.0"
  "eslint-plugin-svelte": "^3.5.1"
  "globals": "^16.1.0"
  "prettier": "^3.2.5"
  "prettier-plugin-svelte": "^3.2.2"
  "publint": "^0.2.7"
  "rimraf": "^5.0.5"
  "svelte-check": "^4.1.7"
  "svelte-preprocess": "^5.1.3"
  "svelte2tsx": "^0.7.6"
  "tslib": "^2.6.2"
  "type-fest": "^4.15.0"
  "typescript-eslint": "^8.32.0"