packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  three: ^0.175.0
  '@types/three': ^0.175.0
  svelte: '5.26.2'
  typescript: '5.9.2'
  vite: '^7.1.4'
  vitest: '^3.2.4'
  '@types/node': '^20.19.4'
  '@types/webxr': '0.5.23'
  '@eslint/js': '^9.26.0'
  'eslint': '^9.26.0'
  '@sveltejs/adapter-auto': '^6.1.0'
  '@sveltejs/kit': '^2.37.0'
  '@sveltejs/package': '^2.3.7'
  '@sveltejs/vite-plugin-svelte': '^6.1.4'
  '@yushijinhun/three-minifier-rollup': '^0.4.0'
  'eslint-plugin-svelte': '^3.5.1'
  'globals': '^16.1.0'
  'prettier': '^3.2.5'
  'prettier-plugin-svelte': '^3.2.2'
  'publint': '^0.2.7'
  'rimraf': '^6.0.1'
  'svelte-check': '^4.3.1'
  'svelte2tsx': '^0.7.6'
  'svelte-tweakpane-ui': '^1.5.9'
  'tslib': '^2.6.2'
  'type-fest': '^4.15.0'
  'typescript-eslint': '^8.32.0'
