/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BodyMesh: THREE.Mesh
    LeftCover: THREE.Mesh
    RightCover: THREE.Mesh
    ScreenFrame: THREE.Mesh
    joystick_base: THREE.Mesh
    joystick_stick_application: THREE.Mesh
    joystick_stick: THREE.Mesh
    joystick_cap: THREE.Mesh
    Screen: THREE.Mesh
  }
  materials: {
    ['machine body main']: THREE.MeshStandardMaterial
    ['machine body outer']: THREE.MeshStandardMaterial
    ['screen frame']: THREE.MeshStandardMaterial
    ['joystick base']: THREE.MeshStandardMaterial
    ['joystick stick']: THREE.MeshStandardMaterial
    ['joystick cap']: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/arcade_machine_own.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BodyMesh.geometry} material={materials['machine body main']} position={[0.2755, 0, 0]} />
      <mesh geometry={nodes.LeftCover.geometry} material={materials['machine body outer']} position={[0.3, 1.2099, -0.1307]} />
      <mesh geometry={nodes.RightCover.geometry} material={materials['machine body outer']} position={[-0.3, 1.2099, -0.1307]} />
      <mesh geometry={nodes.ScreenFrame.geometry} material={materials['screen frame']} position={[0.2755, 0.0633, 0.0346]} />
      <mesh geometry={nodes.joystick_base.geometry} material={materials['joystick base']} position={[0.1336, 0.9611, -0.1976]} rotation={[-0.1939, 0, 0]} scale={[-8.3542, -0.0936, -8.3542]} />
      <mesh geometry={nodes.joystick_stick_application.geometry} material={materials['joystick base']} position={[0.1336, 0.9668, -0.1987]} rotation={[-0.1939, 0, 0]} scale={[-1.5153, -0.1359, -1.5153]}>
        <mesh geometry={nodes.joystick_stick.geometry} material={materials['joystick stick']} position={[0, 0.1066, -0.0001]} scale={[-0.6599, -7.3598, -0.6599]}>
          <mesh geometry={nodes.joystick_cap.geometry} material={materials['joystick cap']} position={[-0.0001, 0.1126, -0.0005]} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.Screen.geometry} material={materials.Screen} position={[0, 1.3774, 0.1447]} scale={1.0055} />
    </group>
  )
}

useGLTF.preload('/arcade_machine_own.glb')
