<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ./Suzanne.glb -t -s
-->
<script lang="ts">
  import { T, useTask } from '@threlte/core'
  import { Float, useGltf } from '@threlte/extras'
  import type * as THREE from 'three'

  type GLTFResult = {
    nodes: {
      Suzanne: THREE.Mesh
      Icosphere: THREE.Mesh
      Cylinder: THREE.Mesh
      Floor: THREE.Mesh
    }
    materials: {
      Mat: THREE.MeshStandardMaterial
    }
  }

  let rotation = $state(0)

  useTask((dt) => {
    rotation += dt
  })

  const gltf = useGltf<GLTFResult>('/models/Suzanne.glb')
</script>

<T.Group dispose={false}>
  {#await gltf then gltf}
    <Float
      floatIntensity={10}
      speed={2}
      floatingRange={[0.15, 0.4]}
    >
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Suzanne.geometry}
        material={gltf.materials.Mat}
        rotation.x={-0.62}
        rotation.y={rotation}
      />
    </Float>

    <Float
      floatIntensity={8}
      seed={1}
      speed={3}
      floatingRange={[0.2, 0.6]}
      position={[2.2, 0, -0.5]}
    >
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Icosphere.geometry}
        material={gltf.materials.Mat}
        rotation.x={-0.62}
        rotation.y={0.09 + rotation}
        rotation.z={1.4 + rotation / 2}
      />
    </Float>

    <Float
      floatIntensity={6}
      seed={2}
      speed={4}
      floatingRange={[0.2, 0.5]}
      position={[-2.4, 0, 0.2]}
    >
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder.geometry}
        material={gltf.materials.Mat}
      />
    </Float>

    <T.Mesh
      receiveShadow
      geometry={gltf.nodes.Floor.geometry}
      material={gltf.materials.Mat}
      position={[0, -0.1, 0]}
    />
  {/await}
</T.Group>
