<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ./Suzanne.glb -t -s
-->
<script lang="ts">
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { Sequence, Sheet, SheetObject } from '@threlte/theatre'
  import type * as THREE from 'three'

  type GLTFResult = {
    nodes: {
      Suzanne: THREE.Mesh
      Icosphere: THREE.Mesh
      Cylinder: THREE.Mesh
      Floor: THREE.Mesh
    }
    materials: {
      Mat: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Suzanne.glb')
</script>

<T.Group dispose={false}>
  {#await gltf then gltf}
    <Sheet name="Suzanne">
      <Sequence
        autoplay
        iterationCount={Infinity}
      />
      <SheetObject key="Suzanne">
        {#snippet children({ Transform })}
          <Transform>
            <T.Mesh
              castShadow
              receiveShadow
              geometry={gltf.nodes.Suzanne.geometry}
              material={gltf.materials.Mat}
              rotation={[-0.62, 0, 0]}
            />
          </Transform>
        {/snippet}
      </SheetObject>
    </Sheet>

    <Sheet name="Icosphere">
      <Sequence
        autoplay
        iterationCount={Infinity}
      />
      <SheetObject key="Icosphere">
        {#snippet children({ Transform })}
          <Transform>
            <T.Mesh
              castShadow
              receiveShadow
              geometry={gltf.nodes.Icosphere.geometry}
              material={gltf.materials.Mat}
              rotation={[-0.62, 0.09, 1.4]}
            />
          </Transform>
        {/snippet}
      </SheetObject>
    </Sheet>

    <Sheet name="Cylinder">
      <Sequence
        autoplay
        iterationCount={Infinity}
      />
      <SheetObject key="Cylinder">
        {#snippet children({ Transform })}
          <Transform>
            <T.Mesh
              castShadow
              receiveShadow
              geometry={gltf.nodes.Cylinder.geometry}
              material={gltf.materials.Mat}
            />
          </Transform>
        {/snippet}
      </SheetObject>
    </Sheet>

    <T.Mesh
      receiveShadow
      geometry={gltf.nodes.Floor.geometry}
      material={gltf.materials.Mat}
      position={[0, -0.1, 0]}
    />
  {/await}
</T.Group>
