<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ./Suzanne.glb -t -s
-->
<script lang="ts">
  import { T, forwardEventHandlers, type Events, type Props, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { Sequence, Sheet, SheetObject } from '@threlte/theatre'
  import type * as THREE from 'three'
  import { Group } from 'three'
  import Suzanne from './Suzanne.glb'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Suzanne: THREE.Mesh
      Icosphere: THREE.Mesh
      Cylinder: THREE.Mesh
      Floor: THREE.Mesh
    }
    materials: {
      Mat: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>(Suzanne)

  const component = forwardEventHandlers()
</script>

<T
  is={ref}
  dispose={false}
  {...$$restProps}
  bind:this={$component}
>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <Sheet name="Suzanne">
      <Sequence
        autoplay
        iterationCount={Infinity}
      />
      <SheetObject
        key="Suzanne"
        let:Transform
      >
        <Transform>
          <T.Mesh
            castShadow
            receiveShadow
            geometry={gltf.nodes.Suzanne.geometry}
            material={gltf.materials.Mat}
            rotation={[-0.62, 0, 0]}
          />
        </Transform>
      </SheetObject>
    </Sheet>

    <Sheet name="Icosphere">
      <Sequence
        autoplay
        iterationCount={Infinity}
      />
      <SheetObject
        key="Icosphere"
        let:Transform
      >
        <Transform>
          <T.Mesh
            castShadow
            receiveShadow
            geometry={gltf.nodes.Icosphere.geometry}
            material={gltf.materials.Mat}
            rotation={[-0.62, 0.09, 1.4]}
          />
        </Transform>
      </SheetObject>
    </Sheet>

    <Sheet name="Cylinder">
      <Sequence
        autoplay
        iterationCount={Infinity}
      />
      <SheetObject
        key="Cylinder"
        let:Transform
      >
        <Transform>
          <T.Mesh
            castShadow
            receiveShadow
            geometry={gltf.nodes.Cylinder.geometry}
            material={gltf.materials.Mat}
          />
        </Transform>
      </SheetObject>
    </Sheet>

    <T.Mesh
      receiveShadow
      geometry={gltf.nodes.Floor.geometry}
      material={gltf.materials.Mat}
      position={[0, -0.1, 0]}
    />
  {:catch error}
    <slot
      name="error"
      {error}
    />
  {/await}

  <slot {ref} />
</T>
