<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 deathValley.glb --transform
Author: artfromheath (https://sketchfab.com/artfromheath)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/death-valley-terrain-9f57bca156e14cff9e4e316a9ccc3e0d
Title: Death Valley - Terrain
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/deathValley.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T
  is={ref}
  dispose={false}
  {...$$restProps}
  bind:this={$component}
>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group
      position={[0, -0.06, 0.06]}
      rotation={[-Math.PI, 0, 0]}
    >
      <T.Mesh
        geometry={gltf.nodes.Object_2.geometry}
        material={gltf.materials.material_0}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_3.geometry}
        material={gltf.materials.material_0}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_4.geometry}
        material={gltf.materials.material_0}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_5.geometry}
        material={gltf.materials.material_0}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_6.geometry}
        material={gltf.materials.material_0}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_7.geometry}
        material={gltf.materials.material_0}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_8.geometry}
        material={gltf.materials.material_0}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_9.geometry}
        material={gltf.materials.material_0}
      />
    </T.Group>
  {:catch error}
    <slot
      name="error"
      {error}
    />
  {/await}

  <slot {ref} />
</T>
