<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 scope.glb
Author: XarMeX (https://sketchfab.com/XarMeX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sniper-scope-nightforce-v2-907abe0a96e243b3b83b6abe47f681b7
Title: Sniper Scope NightForce_V2
-->

<script lang="ts">
  import { CircleGeometry, DoubleSide, Group, MeshBasicMaterial, Texture } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()
  export let scopeViewMap: Texture

  const gltf = useGltf('/models/scope.glb')

  const component = forwardEventHandlers()
</script>

<T
  is={ref}
  dispose={false}
  {...$$restProps}
  bind:this={$component}
  scale={0.02}
>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Object_2.geometry}
      material={gltf.materials.initialShadingGroup}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      position.z={19.5}
      position.y={-0.1}
    >
      <T.CircleGeometry args={[1.8]} />
      <T.MeshBasicMaterial
        side={DoubleSide}
        map={scopeViewMap}
      />
    </T.Mesh>
  {:catch error}
    <slot
      name="error"
      {error}
    />
  {/await}

  <slot {ref} />
</T>
