<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 scope.glb
Author: XarMeX (https://sketchfab.com/XarMeX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sniper-scope-nightforce-v2-907abe0a96e243b3b83b6abe47f681b7
Title: Sniper Scope NightForce_V2
-->

<script lang="ts">
  import { Group, type Vector3Tuple, MathUtils } from 'three'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { Tween } from 'svelte/motion'
  import { scoping } from '../Controls.svelte'
  import type { Snippet } from 'svelte'

  interface Props {
    children?: Snippet<[{ ref: Group }]>
  }

  let { children }: Props = $props()

  const group = new Group()

  const gltf = useGltf('/models/scope.glb')

  const rotationX = new Tween(-3)
  const position = new Tween<Vector3Tuple>([0.4, -0.15, -1])

  $effect.pre(() => {
    if ($scoping) {
      rotationX.set(0)
      position.set([0, 0, -0.496])
    } else {
      rotationX.set(-3)
      position.set([0.4, -0.15, -1])
    }
  })
</script>

<T
  is={group}
  dispose={false}
  scale={0.02}
  position={position.current}
  rotation.y={MathUtils.DEG2RAD * rotationX.current}
>
  {#await gltf then { nodes, materials }}
    <T.Mesh
      geometry={nodes.Object_2.geometry}
      material={materials.initialShadingGroup}
      rotation={[-Math.PI / 2, 0, 0]}
    />
  {/await}

  {@render children?.({ ref: group })}
</T>
