<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /Users/grischaerbe/Documents/Projects/2022/threlte/apps/godzilla/static/models/archery-target.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { AutoColliders, RigidBody } from '@threlte/rapier'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Cylinder016: THREE.Mesh
			Cylinder016_1: THREE.Mesh
			Cylinder016_2: THREE.Mesh
		}
		materials: {
			['Red.025']: THREE.MeshStandardMaterial
			['White.025']: THREE.MeshStandardMaterial
			['BrownDark.018']: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>(
		'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/target-stand/model.gltf'
	)

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<RigidBody type="fixed">
			<AutoColliders shape="convexHull">
				<T.Group rotation={[Math.PI / 2, 0, 0]}>
					<T.Mesh geometry={gltf.nodes.Cylinder016.geometry} material={gltf.materials['Red.025']} />
					<T.Mesh
						geometry={gltf.nodes.Cylinder016_1.geometry}
						material={gltf.materials['White.025']}
					/>
					<T.Mesh
						geometry={gltf.nodes.Cylinder016_2.geometry}
						material={gltf.materials['BrownDark.018']}
					/>
				</T.Group>
			</AutoColliders>
		</RigidBody>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
