<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /Users/grischaerbe/Documents/Projects/2022/threlte/apps/godzilla/static/models/Bell_Tower.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Cube296: THREE.Mesh
			Cube296_1: THREE.Mesh
			Cube296_2: THREE.Mesh
			Cube296_3: THREE.Mesh
			Cube296_4: THREE.Mesh
			Cube296_5: THREE.Mesh
			Cube296_6: THREE.Mesh
			Cube296_7: THREE.Mesh
			Cube296_8: THREE.Mesh
			Cube296_9: THREE.Mesh
		}
		materials: {
			Stone_Light: THREE.MeshStandardMaterial
			Stone_Dark: THREE.MeshStandardMaterial
			Wood: THREE.MeshStandardMaterial
			Beige: THREE.MeshStandardMaterial
			Wood_Side: THREE.MeshStandardMaterial
			Windows: THREE.MeshStandardMaterial
			Wood_Light: THREE.MeshStandardMaterial
			Bell: THREE.MeshStandardMaterial
			RoofTiles: THREE.MeshStandardMaterial
			Stone: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/models/Bell_Tower.glb')

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} scale={4}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Cube296.geometry} material={gltf.materials.Stone_Light} />
		<T.Mesh geometry={gltf.nodes.Cube296_1.geometry} material={gltf.materials.Stone_Dark} />
		<T.Mesh geometry={gltf.nodes.Cube296_2.geometry} material={gltf.materials.Wood} />
		<T.Mesh geometry={gltf.nodes.Cube296_3.geometry} material={gltf.materials.Beige} />
		<T.Mesh geometry={gltf.nodes.Cube296_4.geometry} material={gltf.materials.Wood_Side} />
		<T.Mesh geometry={gltf.nodes.Cube296_5.geometry} material={gltf.materials.Windows} />
		<T.Mesh geometry={gltf.nodes.Cube296_6.geometry} material={gltf.materials.Wood_Light} />
		<T.Mesh geometry={gltf.nodes.Cube296_7.geometry} material={gltf.materials.Bell} />
		<T.Mesh geometry={gltf.nodes.Cube296_8.geometry} material={gltf.materials.RoofTiles} />
		<T.Mesh geometry={gltf.nodes.Cube296_9.geometry} material={gltf.materials.Stone} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
