<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /Users/grischaerbe/Documents/Projects/2022/threlte/apps/godzilla/static/models/Bow.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import { T, forwardEventHandlers, type Events, type Slots } from '@threlte/core'
	import { useGltf, useGltfAnimations } from '@threlte/extras'
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { DEG2RAD } from 'three/src/math/MathUtils'

	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type ActionName = 'Armature|ArmatureAction.001'
	type GLTFResult = {
		nodes: {
			Object_9: THREE.SkinnedMesh
			_rootJoint: THREE.Bone
		}
		materials: {
			['Material.003']: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/models/Bow.glb')
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} bind:this={$component} scale={0.3} rotation.y={90 * DEG2RAD}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Bow_Group">
				<T.Group
					name="PBR_Low-poly_Game-ready_Asset_-_Bow_and_Arrow"
					position={[-0.05, -0.62, 1.61]}
					scale={0.01}
				>
					<T.Group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
						<T.Group name="Object_6">
							<T.Group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
							<T is={gltf.nodes._rootJoint} />
							<T.SkinnedMesh
								name="Object_9"
								geometry={gltf.nodes.Object_9.geometry}
								material={gltf.materials['Material.003']}
								skeleton={gltf.nodes.Object_9.skeleton}
							/>
						</T.Group>
					</T.Group>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
