<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /Users/grischaerbe/Documents/Projects/2022/threlte/apps/godzilla/static/models/CompositionB.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf, useGltfAnimations } from '@threlte/extras'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type ActionName = 'BladeAction'
	type GLTFResult = {
		nodes: {
			Blade: THREE.Mesh
			CompositionB: THREE.Mesh
		}
		materials: {
			composition_A: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/models/CompositionB.glb')
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

	$: $actions.BladeAction?.play()

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Scene_1">
				<T.Mesh
					name="Blade"
					geometry={gltf.nodes.Blade.geometry}
					material={gltf.materials.composition_A}
					position={[-2.74, 5.13, 7.72]}
					rotation={[0, 0.32, 0]}
				/>
				<T.Mesh
					name="CompositionB"
					geometry={gltf.nodes.CompositionB.geometry}
					material={gltf.materials.composition_A}
					position={[-2.12, 0.06, 2.22]}
					rotation={[-Math.PI, 0.61, -Math.PI]}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
