<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /Users/grischaerbe/Documents/Projects/2022/threlte/apps/godzilla/static/models/Ground.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import { AutoColliders, RigidBody } from '@threlte/rapier'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Plane: THREE.Mesh
		}
		materials: {
			['Material.001']: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/models/Ground.glb')

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<RigidBody type="fixed">
			<AutoColliders shape="trimesh">
				<T.Mesh
					teleportSurface
					geometry={gltf.nodes.Plane.geometry}
					material={gltf.materials['Material.001']}
					scale={40}
				/>
			</AutoColliders>
		</RigidBody>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
