<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /Users/grischaerbe/Documents/Projects/2022/threlte/apps/godzilla/static/models/House_2.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Cylinder021: THREE.Mesh
			Cylinder021_1: THREE.Mesh
			Cylinder021_2: THREE.Mesh
			Cylinder021_3: THREE.Mesh
			Cylinder021_4: THREE.Mesh
			Cylinder021_5: THREE.Mesh
			Cylinder021_6: THREE.Mesh
			Cylinder021_7: THREE.Mesh
			Cylinder021_8: THREE.Mesh
		}
		materials: {
			Beige: THREE.MeshStandardMaterial
			Wood: THREE.MeshStandardMaterial
			Stone_Dark: THREE.MeshStandardMaterial
			Windows: THREE.MeshStandardMaterial
			Wood_Light: THREE.MeshStandardMaterial
			RoofTiles: THREE.MeshStandardMaterial
			Stone_Light: THREE.MeshStandardMaterial
			Wood_Side: THREE.MeshStandardMaterial
			Stone: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/models/House_2.glb')

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} scale={4}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Cylinder021.geometry} material={gltf.materials.Beige} />
		<T.Mesh geometry={gltf.nodes.Cylinder021_1.geometry} material={gltf.materials.Wood} />
		<T.Mesh geometry={gltf.nodes.Cylinder021_2.geometry} material={gltf.materials.Stone_Dark} />
		<T.Mesh geometry={gltf.nodes.Cylinder021_3.geometry} material={gltf.materials.Windows} />
		<T.Mesh geometry={gltf.nodes.Cylinder021_4.geometry} material={gltf.materials.Wood_Light} />
		<T.Mesh geometry={gltf.nodes.Cylinder021_5.geometry} material={gltf.materials.RoofTiles} />
		<T.Mesh geometry={gltf.nodes.Cylinder021_6.geometry} material={gltf.materials.Stone_Light} />
		<T.Mesh geometry={gltf.nodes.Cylinder021_7.geometry} material={gltf.materials.Wood_Side} />
		<T.Mesh geometry={gltf.nodes.Cylinder021_8.geometry} material={gltf.materials.Stone} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
