<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /Users/grischaerbe/Documents/Projects/2022/threlte/apps/godzilla/static/models/House_1.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Cube145: THREE.Mesh
			Cube145_1: THREE.Mesh
			Cube145_2: THREE.Mesh
			Cube145_3: THREE.Mesh
			Cube145_4: THREE.Mesh
			Cube145_5: THREE.Mesh
			Cube145_6: THREE.Mesh
			Cube145_7: THREE.Mesh
			Cube145_8: THREE.Mesh
		}
		materials: {
			Plaster: THREE.MeshStandardMaterial
			Wood: THREE.MeshStandardMaterial
			Wood_Side: THREE.MeshStandardMaterial
			Windows: THREE.MeshStandardMaterial
			Wood_Light: THREE.MeshStandardMaterial
			Stone_Dark: THREE.MeshStandardMaterial
			Stone: THREE.MeshStandardMaterial
			RoofTiles: THREE.MeshStandardMaterial
			Stone_Light: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/models/House_1.glb')

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} scale={4}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Cube145.geometry} material={gltf.materials.Plaster} />
		<T.Mesh geometry={gltf.nodes.Cube145_1.geometry} material={gltf.materials.Wood} />
		<T.Mesh geometry={gltf.nodes.Cube145_2.geometry} material={gltf.materials.Wood_Side} />
		<T.Mesh geometry={gltf.nodes.Cube145_3.geometry} material={gltf.materials.Windows} />
		<T.Mesh geometry={gltf.nodes.Cube145_4.geometry} material={gltf.materials.Wood_Light} />
		<T.Mesh geometry={gltf.nodes.Cube145_5.geometry} material={gltf.materials.Stone_Dark} />
		<T.Mesh geometry={gltf.nodes.Cube145_6.geometry} material={gltf.materials.Stone} />
		<T.Mesh geometry={gltf.nodes.Cube145_7.geometry} material={gltf.materials.RoofTiles} />
		<T.Mesh geometry={gltf.nodes.Cube145_8.geometry} material={gltf.materials.Stone_Light} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
