<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /Users/grischaerbe/Documents/Projects/2022/threlte/apps/godzilla/static/models/Mill.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import {
		T,
		type Props,
		type Events,
		type Slots,
		forwardEventHandlers,
		useFrame
	} from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Cube128: THREE.Mesh
			Cube128_1: THREE.Mesh
			Cube128_2: THREE.Mesh
			Cube128_3: THREE.Mesh
			Cube128_4: THREE.Mesh
			Cube128_5: THREE.Mesh
			Cube128_6: THREE.Mesh
			Cube128_7: THREE.Mesh
			Cube128_8: THREE.Mesh
			Cube128_9: THREE.Mesh
			Cube007: THREE.Mesh
			Cube007_1: THREE.Mesh
			Cube007_2: THREE.Mesh
			Cube007_3: THREE.Mesh
		}
		materials: {
			RoofTiles: THREE.MeshStandardMaterial
			Stone_Light: THREE.MeshStandardMaterial
			Stone_Dark: THREE.MeshStandardMaterial
			Wood: THREE.MeshStandardMaterial
			Windows: THREE.MeshStandardMaterial
			Wood_Light: THREE.MeshStandardMaterial
			Plaster: THREE.MeshStandardMaterial
			Wood_Side: THREE.MeshStandardMaterial
			Green: THREE.MeshStandardMaterial
			Stone: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/models/Mill.glb')

	const component = forwardEventHandlers()

	let rotation = 0
	useFrame((_, delta) => {
		rotation += delta * 0.5
	})
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} scale={4}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[0.01, 0, 0]}>
			<T.Mesh geometry={gltf.nodes.Cube128.geometry} material={gltf.materials.RoofTiles} />
			<T.Mesh geometry={gltf.nodes.Cube128_1.geometry} material={gltf.materials.Stone_Light} />
			<T.Mesh geometry={gltf.nodes.Cube128_2.geometry} material={gltf.materials.Stone_Dark} />
			<T.Mesh geometry={gltf.nodes.Cube128_3.geometry} material={gltf.materials.Wood} />
			<T.Mesh geometry={gltf.nodes.Cube128_4.geometry} material={gltf.materials.Windows} />
			<T.Mesh geometry={gltf.nodes.Cube128_5.geometry} material={gltf.materials.Wood_Light} />
			<T.Mesh geometry={gltf.nodes.Cube128_6.geometry} material={gltf.materials.Plaster} />
			<T.Mesh geometry={gltf.nodes.Cube128_7.geometry} material={gltf.materials.Wood_Side} />
			<T.Mesh geometry={gltf.nodes.Cube128_8.geometry} material={gltf.materials.Green} />
			<T.Mesh geometry={gltf.nodes.Cube128_9.geometry} material={gltf.materials.Stone} />
		</T.Group>
		<T.Group position={[0.01, 3.12, 0.87]} rotation.z={rotation}>
			<T.Mesh geometry={gltf.nodes.Cube007.geometry} material={gltf.materials.Wood} />
			<T.Mesh geometry={gltf.nodes.Cube007_1.geometry} material={gltf.materials.Plaster} />
			<T.Mesh geometry={gltf.nodes.Cube007_2.geometry} material={gltf.materials.Wood_Side} />
			<T.Mesh geometry={gltf.nodes.Cube007_3.geometry} material={gltf.materials.Wood_Light} />
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
