<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 Dragon_Evolved.gltf --transform --types
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group, Vector3 } from 'three'
  import { T, type Props, type Events, type Slots, useFrame, useThrelte } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type ActionName =
    | 'Death'
    | 'Fast_Flying'
    | 'Flying_Idle'
    | 'Headbutt'
    | 'HitReact'
    | 'No'
    | 'Punch'
    | 'Yes'
  type GLTFResult = {
    nodes: {
      Cube221: THREE.SkinnedMesh
      Cube221_1: THREE.SkinnedMesh
      Cube221_2: THREE.SkinnedMesh
      Cube221_3: THREE.SkinnedMesh
      Cube221_4: THREE.SkinnedMesh
      Root: THREE.Bone
    }
    materials: {
      Dragon_Main: THREE.MeshStandardMaterial
      Dragon_Secondary: THREE.MeshStandardMaterial
      Dragon_Horn: THREE.MeshStandardMaterial
      Eye_Black: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Dragon_Evolved-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  $: $actions.Flying_Idle?.play()

  import { clippyStores } from './clippyStores'
  import { domTo3dPos } from './clippyUtil'
  const { clippyRect } = clippyStores

  let pos = new Vector3()

  const { camera } = useThrelte()

  $: {
    if ($clippyRect) {
      pos = domTo3dPos($clippyRect, $camera)
    }
  }
</script>

{#if $gltf}
  <T
    is={ref}
    dispose={false}
    position={pos.toArray()}
    {...$$restProps}
  >
    <T.Group name="Scene">
      <T.Group name="CharacterArmature">
        <T is={$gltf.nodes.Root} />
        <T.Group name="Dragon">
          <T.SkinnedMesh
            name="Cube221"
            geometry={$gltf.nodes.Cube221.geometry}
            material={$gltf.materials.Dragon_Main}
            skeleton={$gltf.nodes.Cube221.skeleton}
          />
          <T.SkinnedMesh
            name="Cube221_1"
            geometry={$gltf.nodes.Cube221_1.geometry}
            material={$gltf.materials.Dragon_Secondary}
            skeleton={$gltf.nodes.Cube221_1.skeleton}
          />
          <T.SkinnedMesh
            name="Cube221_2"
            geometry={$gltf.nodes.Cube221_2.geometry}
            material={$gltf.materials.Dragon_Horn}
            skeleton={$gltf.nodes.Cube221_2.skeleton}
          />
          <T.SkinnedMesh
            name="Cube221_3"
            geometry={$gltf.nodes.Cube221_3.geometry}
            material={$gltf.materials.Eye_Black}
            skeleton={$gltf.nodes.Cube221_3.skeleton}
          />
          <T.SkinnedMesh
            name="Cube221_4"
            geometry={$gltf.nodes.Cube221_4.geometry}
            material={$gltf.materials.Dragon_Horn}
            skeleton={$gltf.nodes.Cube221_4.skeleton}
          />
        </T.Group>
      </T.Group>
    </T.Group>

    <slot {ref} />
  </T>
{/if}
