<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./cube.glb -t
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Cube: THREE.Mesh
		}
		materials: {}
	}

	const gltf = useGltf<GLTFResult>('/cube.glb')

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Cube.geometry}>
			<T is={gltf.nodes.Cube.material} />
		</T.Mesh>
	{:catch error}
		<slot name="error" {error} />
	{/await}
</T>
