<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 /Users/michealparks/Desktop/spaceship.glb -s -o -u -T -R
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rusty-spaceship-orange-18541ebed6ce44a9923f9b8dc30d87f5
Title: Rusty Spaceship - Orange
-->

<script lang="ts">
  import { T } from '@threlte/core'
  import { useGltf, useDraco, useSuspense } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const suspend = useSuspense()

  const dracoLoader = useDraco()
  const gltf = suspend(
    useGltf('/spaceship-transformed.glb', {
      dracoLoader
    })
  )
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube001_spaceship_racer_0.geometry}
      material={gltf.materials.spaceship_racer}
      position={[7.39, -0.65, 0.65]}
      scale={0.01}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube005_cockpit_0.geometry}
      material={gltf.materials.cockpit}
      position={[7.39, 1.1, 3.07]}
      rotation={[0.09, 0, 0]}
      scale={0.01}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
