
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.1 test.glb -t
-->




    <script lang="ts">


import type * as THREE from 'three'
  import type { Snippet } from 'svelte'
        import { T, type Props } from '@threlte/core'
        import { useGltf } from '@threlte/extras'


        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        }: Props<THREE.Group> & {
          ref?: THREE.Group
          children?: Snippet<[{ ref: THREE.Group }]>
          fallback?: Snippet
          error?: Snippet<[{ error: Error }]>
        } = $props()



        type GLTFResult = {
    nodes: {
      ['balcony-floor-center_1']: THREE.Mesh

    }
    materials: {
      colormap: THREE.MeshStandardMaterial
    }
  }

        const gltf = useGltf<GLTFResult>('/test.glb')

    </script>

		<T.Group bind:ref dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Mesh geometry={gltf.nodes['balcony-floor-center_1'].geometry} material={gltf.materials.colormap} />

			{:catch error}
        {@render error?.({ error })}
			{/await}

      {@render children?.({ ref })}
		</T.Group>
