<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 E:\projects\2024\model\static\models\duck_floaty.glb --root /models/ --types --printwidth 120 --precision 2 --draco true --transform --resolution 1024 --simplify --weld 0.001 --ratio 0.0075 --error 1e-9
Author: raholder0909 (https://sketchfab.com/raholder0909)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/duck-floaty-1467f79dc22e46c49e68a688865e9f70
Title: duck floaty
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { T } from '@threlte/core'
  import { useGltf, InstancedMeshes } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      Object_4: THREE.Mesh
      Object_6: THREE.Mesh
    }
    materials: {
      bill: THREE.MeshStandardMaterial
      duck_body: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/duck_floaty-transformed.glb', { useDraco: true })

  const duckSpread = 200
</script>

<T.Group
  dispose={false}
  frustumCulled={false}
>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <InstancedMeshes meshes={gltf.nodes}>
      {#snippet children({ components: { Object_4, Object_6 } })}
        {#each { length: 200 } as _}
          {@const posX = Math.random() * duckSpread - duckSpread / 2}
          {@const posZ = Math.random() * duckSpread - 300}
          <T.Group
            position.x={posX}
            position.z={posZ}
            scale={0.1}
          >
            <Object_4
              position={[0, 1.59, 2.54]}
              scale={0.43}
            />
            <Object_6 position={[0, -0.03, 0]} />
          </T.Group>
        {/each}
      {/snippet}
    </InstancedMeshes>
  {/await}
</T.Group>
