<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\Aaron\Documents\FunBit\static\models\BirchTree_1.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useTexture } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Cube004: THREE.Mesh;
			Cube004_1: THREE.Mesh;
		};
		materials: {
			BirchTree_Bark: THREE.MeshStandardMaterial;
			BirchTree_Leaves: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('https://fun-bit.vercel.app/Ultimate-Stylized-Nature/BirchTree_1.gltf');
	const texture1 = useTexture('https://fun-bit.vercel.app/Ultimate-Stylized-Nature/Textures/BirchTree_Bark.png');
	const normalMap1 = useTexture('https://fun-bit.vercel.app/Ultimate-Stylized-Nature/Textures/BirchTree_Bark_Normal.png');
	const texture2 = useTexture('https://fun-bit.vercel.app/Ultimate-Stylized-Nature/Textures/BirchTree_Leaves.png');

	const assets = Promise.all([gltf, texture1, texture2, normalMap1]);

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await assets}
		<slot name="fallback" />
	{:then [gltf, t1, t2, n1]}
		<T.Mesh geometry={gltf.nodes.Cube004.geometry}>
			<T.MeshStandardMaterial
				map={t1}
				map.wrapS={THREE.RepeatWrapping}
				map.wrapT={THREE.RepeatWrapping}
				normalMap={n1}
				normalMap.wrapS={THREE.RepeatWrapping}
				normalMap.wrapT={THREE.RepeatWrapping} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube004_1.geometry}>
			<T.MeshStandardMaterial map={t2} side={THREE.DoubleSide} alphaTest={0.5} />
		</T.Mesh>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
