<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.5 apps/docs/public/models/RobotExpressive.glb --types --root /models/ --output apps/docs/src/examples/gltf/skinned-meshes/Robot.svelte
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { clone as cloneSkeleton } from 'three/examples/jsm/utils/SkeletonUtils.js'
  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type ActionName =
    | 'Dance'
    | 'Death'
    | 'Idle'
    | 'Jump'
    | 'No'
    | 'Punch'
    | 'Running'
    | 'Sitting'
    | 'Standing'
    | 'ThumbsUp'
    | 'Walking'
    | 'WalkJump'
    | 'Wave'
    | 'Yes'
  type GLTFResult = {
    nodes: {
      FootL_1: THREE.Mesh
      LowerLegL_1: THREE.Mesh
      LegL: THREE.Mesh
      LowerLegR_1: THREE.Mesh
      LegR: THREE.Mesh
      Head_2: THREE.Mesh
      Head_3: THREE.Mesh
      Head_4: THREE.Mesh
      ArmL: THREE.Mesh
      ShoulderL_1: THREE.Mesh
      ArmR: THREE.Mesh
      ShoulderR_1: THREE.Mesh
      Torso_2: THREE.Mesh
      Torso_3: THREE.Mesh
      FootR_1: THREE.Mesh
      HandR_1: THREE.SkinnedMesh
      HandR_2: THREE.SkinnedMesh
      HandL_1: THREE.SkinnedMesh
      HandL_2: THREE.SkinnedMesh
      Bone: THREE.Bone
    }
    materials: {
      Grey: THREE.MeshStandardMaterial
      Main: THREE.MeshStandardMaterial
      Black: THREE.MeshStandardMaterial
    }
  }

  let {
    fallback,
    error,
    children,
    action,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    action?: ActionName
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  ref = new Group()

  const gltf = useGltf<GLTFResult>('/models/RobotExpressive.glb')

  function cloneScene(scene: THREE.Group) {
    const clone = cloneSkeleton(scene)
    const nodes: Record<string, THREE.Object3D> = {}
    clone.traverse((child) => {
      if (child.name) nodes[child.name] = child
    })
    return nodes as unknown as GLTFResult['nodes']
  }

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  $effect(() => {
    if (action) $actions?.[action]?.play()
  })
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    {@const clonedNodes = cloneScene(gltf.scene)}
    <T.Group name="Root_Scene">
      <T.Group name="RootNode">
        <T.Group
          name="RobotArmature"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T is={clonedNodes.Bone} />
        </T.Group>
        <T.Group
          name="HandR"
          position={[0, 2.37, -0.02]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T.SkinnedMesh
            name="HandR_1"
            geometry={gltf.nodes.HandR_1.geometry}
            material={gltf.materials.Main}
            skeleton={clonedNodes.HandR_1.skeleton}
          />
          <T.SkinnedMesh
            name="HandR_2"
            geometry={gltf.nodes.HandR_2.geometry}
            material={gltf.materials.Grey}
            skeleton={clonedNodes.HandR_2.skeleton}
          />
        </T.Group>
        <T.Group
          name="HandL"
          position={[0, 2.37, -0.02]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T.SkinnedMesh
            name="HandL_1"
            geometry={gltf.nodes.HandL_1.geometry}
            material={gltf.materials.Main}
            skeleton={clonedNodes.HandL_1.skeleton}
          />
          <T.SkinnedMesh
            name="HandL_2"
            geometry={gltf.nodes.HandL_2.geometry}
            material={gltf.materials.Grey}
            skeleton={clonedNodes.HandL_2.skeleton}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
