name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm 🔧
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Lint 💅
        run: pnpm run lint

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm 🔧
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Check
        run: pnpm run check

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm 🔧
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Test
        run: pnpm run test
